### ISSUE TITLE
My corruptor, which is no longer public, is mirrored on this site.

### ISSUE THREAD

**Issue by AliceTS1337** [x8BitRain/corruption-wiki-media#12]
Hi there, a while ago I decided to stop distributing my corruptor as it quickly became obsolete against the new ProcessStub on RTC.

This meant that I removed the original download for it and no longer wanted it to be public.

I see now that it has appeared on this corruption wiki site instead, and no one had asked me for permission to post it there.

Can I contact anyone that handles entries on this site just so we can like, I dunno. talk things through. 

// Sincerely, AliceTS.

**Comment by x8BitRain** [comment]
Hey, what's the name of the corrupter? We can remove it if you want. We like to archive stuff on the site like this to preserve the history of corruption software but if you don't want it public we can change that.
